momw/chroniko/urls.py
from django.conf import settings
from django.urls import path
from django.views.decorators.cache import cache_page
from .feeds import LatestEntriesFeed
from .views import (
    AllEntriesView,
    CategoryDetailView,
    CategoryIndexView,
    DraftEntriesView,
    EntriesByDayView,
    EntriesByMonthView,
    EntriesByYearView,
    EntryDetailView,
    EntryIndexView,
    HiddenEntriesView,
    TagCloudView,
    TagDetailView,
    category_create,
    category_delete,
    category_edit,
    entry_create,
    entry_delete,
    entry_edit,
    tag_edit,
)


app_name = "chroniko"  # TODO: DRY this
urlpatterns = [
    path("", EntryIndexView.as_view(), name="index"),
    path("categories/", CategoryIndexView.as_view(), name="category_index"),
    path("categories/new/", category_create, name="new_category"),
    path(
        "categories/<slug:slug>/", CategoryDetailView.as_view(), name="category_detail"
    ),
    path("categories/<slug:slug>/delete/", category_delete, name="category_delete"),
    path("categories/<slug:slug>/edit/", category_edit, name="category_edit"),
    path("drafts/", DraftEntriesView.as_view(), name="draft_entries"),
    path("entries/all/", AllEntriesView.as_view(), name="all_entries"),
    path("entries/new/", entry_create, name="new_entry"),
    path(
        "feeds/latest-entries/",
        cache_page(settings.CACHE_MIDDLEWARE_SECONDS)(LatestEntriesFeed()),
        name="latest_entries_feed",
    ),
    path("hidden/", HiddenEntriesView.as_view(), name="hidden_entries"),
    path("tag/cloud/", TagCloudView.as_view(), name="tag_cloud"),
    path("tag/<slug:slug>/", TagDetailView.as_view(), name="tag_detail"),
    path("tag/<slug:slug>/edit/", tag_edit, name="tag_edit"),
    path("<slug:slug>/delete/", entry_delete, name="entry_delete"),
    path("<slug:slug>/edit/", entry_edit, name="entry_edit"),
    path("<int:year>/", EntriesByYearView.as_view(), name="by_year"),
    path("<int:year>/<int:month>/", EntriesByMonthView.as_view(), name="by_month"),
    path(
        "<int:year>/<int:month>/<int:day>/", EntriesByDayView.as_view(), name="by_day"
    ),
    path(
        "<int:year>/<int:month>/<int:day>/<slug:slug>/",
        EntryDetailView.as_view(),
        name="entry_detail",
    ),
]

momw/media/urls.py
from django.conf import settings
from django.urls import path
from django.views.decorators.cache import cache_page

# from django.contrib.auth.decorators import login_required
from .feeds import LatestMediaFeed
from .views import (
    LiveAsciinemaView,
    LiveAudioView,
    LiveMediaTracksView,
    LiveVideoView,
    MediaTrackDetailView,
    create_mediatrack,
    edit_mediatrack,
    live_images,
)

app_name = "media"  # TODO: DRY this
urlpatterns = [
    path("", LiveMediaTracksView.as_view(), name="index"),
    path("asciinema/", LiveAsciinemaView.as_view(), name="live_asciinema"),
    path("audio/", LiveAudioView.as_view(), name="live_audio"),
    path(
        "feeds/latest-media/",
        cache_page(settings.CACHE_MIDDLEWARE_SECONDS)(LatestMediaFeed()),
        name="latest_media_feed",
    ),
    path("images/", live_images, name="live_images"),
    path("video/", LiveVideoView.as_view(), name="live_video"),
    path("new/", create_mediatrack, name="create"),
    path("<slug:slug>/", MediaTrackDetailView.as_view(), name="detail"),
    path("<slug:slug>/edit/", edit_mediatrack, name="edit"),
]

momw/momw/urls.py
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path
from django.views.decorators.cache import cache_page
from chroniko.views import EntryDetailView, entry_edit
from utilz.views import app_info, app_info_json
from .feeds import LatestModsFeed
from .settings import CACHE_MIDDLEWARE_SECONDS, DEBUG, USE_ROBOTS
from .sitemaps import sitemap_dict
from .views import search
from .views.dynamicpages import (
    all_mods,
    all_fallback_archives,
    all_groundcover,
    all_plugins,
    categories,
    category_detail,
    compat_unknown,
    example_mod_page,
    fully_working,
    index,
    ip_address,
    latest_mods,
    mod_alts,
    mod_detail,
    mod_list_changelog,
    mod_list_detail,
    mod_list_final,
    mod_list_step_detail,
    mod_lists,
    no_plugin,
    not_working,
    partial_working,
    rn,
    tag_detail,
    tags,
    user_settings,
    users_guide,
    with_plugin,
)
from .views.forms import cfg_generator, cfg_blank
from .views.utility import robots_txt, legacy_url_redirect, static_view, webmanifest


urlpatterns = [
    path("ip", ip_address, name="ip"),
    path("rn", rn, name="rn"),
    path("manifest.webmanifest", webmanifest, name="webmanifest"),
    path("_app/", app_info, name="app-info"),
    path("_stat/", app_info_json, name="app-info-json"),
    path("about/", static_view, {"template": "about.html"}, name="about"),
    path("all-fallback-archives/", all_fallback_archives),
    path("all-groundcover/", all_groundcover),
    path("all-plugins/", all_plugins),
    path("blog/", include("chroniko.urls", namespace="blog")),
    path("cfg-generator/", cfg_blank, name="cfg_generator"),
    path("cfg-generator/<slug:preset>/", cfg_generator, name="cfg_generator"),
    path(
        "cfg-generator/<slug:preset>/json",
        cfg_generator,
        {"as_json": True},
        name="cfg_generator_json",
    ),
    path("cfg/generator/", cfg_blank, name="cfg_generator2"),
    path("cfg/generator/<slug:preset>/", cfg_generator, name="cfg_generator2"),
    path("cfg/", cfg_blank, name="cfg_generator3"),
    path("cfg/<slug:preset>/", cfg_generator, name="cfg_generator3"),
    path(
        "changelogs/", static_view, {"template": "changelogs.html"}, name="changelogs"
    ),
    path(
        "changelogs/website/",
        static_view,
        {"template": "changelogs-website.html"},
        name="changelogs-website",
    ),
    path(
        "compatibility/",
        static_view,
        {"template": "compatibility.html"},
        name="compatibility",
    ),
    path("compat/fully-working/", fully_working, name="fully_working"),
    path("compat/partially-working/", partial_working, name="partial_working"),
    path("compat/not-working/", not_working, name="not_working"),
    path("compat/unknown/", compat_unknown, name="compat_unknown"),
    path("settings/", user_settings, name="user_settings"),
    path("subscribe/", static_view, {"template": "subscribe.html"}, name="subscribe"),
    # path("contact/", contact, name="contact"),
    path("cookie/", static_view, {"template": "cookie.html"}, name="cookie"),
    path(
        "enable-in-cfg-generator-button/",
        static_view,
        {"template": "enable-in-cfg-generator-button.html"},
        name="enable-in-cfg-generator-button",
    ),
    path("faq/", static_view, {"template": "faq.html"}, name="faq"),
    path(
        "faq/tooling", static_view, {"template": "faq-tooling.html"}, name="faq-tooling"
    ),
    # path("feedback/", feedback, name="feedback"),
    path(
        "feeds/mods/",
        cache_page(CACHE_MIDDLEWARE_SECONDS)(LatestModsFeed()),
        name="mod_feed",
    ),
    path(
        "site-update-2022-06-01/",
        legacy_url_redirect,
        {"new_view": "about"},
        name="future_plans",
    ),
    path(
        "getting-started/",
        static_view,
        {"template": "getting_started.html"},
        name="getting_started",
    ),
    path(
        "getting-started/buy/", static_view, {"template": "gs_buy.html"}, name="gs-buy"
    ),
    path(
        "getting-started/install/",
        static_view,
        {"template": "gs_install.html"},
        name="gs-install",
    ),
    path(
        "getting-started/settings/",
        static_view,
        {"template": "gs_settings.html"},
        name="gs-settings",
    ),
    path(
        "getting-started/managing-mods/",
        legacy_url_redirect,
        {"new_view": "guides-users"},
        name="gs-directories",
    ),
    path(
        "getting-started/directories/",
        legacy_url_redirect,
        {"new_view": "guides-users"},
        name="gs-directories-old",
    ),
    path(
        "getting-started/tips/",
        static_view,
        {"template": "gs_tips.html"},
        name="gs-tips",
    ),
    path("guides/", static_view, {"template": "guides.html"}, name="guides"),
    path(
        "guides/developers/",
        static_view,
        {"template": "guides_developers.html"},
        name="guides-developers",
    ),
    path(
        "guides/modders/",
        static_view,
        {"template": "guides_modders.html"},
        name="guides-modders",
    ),
    path("guides/users/", users_guide, name="guides-users"),
    path("lists/", mod_lists, name="mod-lists"),
    path("lists/add/", static_view, {"template": "add_a_list.html"}, name="add-a-list"),
    # START legacy list URLs
    path(
        "lists/androidswitch/",
        legacy_url_redirect,
        {"new_slug": "i-heart-vanilla-directors-cut", "new_view": "mod-list-detail"},
        name="old-androidswitch-list",
    ),
    path(
        "lists/tes3mp-friendly/",
        legacy_url_redirect,
        {"new_slug": "tes3mp-server", "new_view": "mod-list-detail"},
        name="old-tes3mp-list",
    ),
    # "Legacy" lists; point them to the actual new ones
    path(
        "lists/legacy-expanded-vanilla/",
        legacy_url_redirect,
        {"new_slug": "expanded-vanilla", "new_view": "mod-list-detail"},
        name="legacy-lists-expanded-vanilla",
    ),
    path(
        "lists/legacy-graphics-overhaul/",
        legacy_url_redirect,
        {"new_slug": "graphics-overhaul", "new_view": "mod-list-detail"},
        name="legacy-lists-graphics-overhaul",
    ),
    path(
        "lists/legacy-total-overhaul/",
        legacy_url_redirect,
        {"new_slug": "total-overhaul", "new_view": "mod-list-detail"},
        name="legacy-lists-total-overhaul",
    ),
    # END legacy list URLs
    path("lists/<slug:slug>/", mod_list_detail, name="mod-list-detail"),
    path(
        "lists/<slug:slug>/json",
        mod_list_detail,
        {"as_json": True},
        name="mod-list-detail-json",
    ),
    path("lists/<slug:slug>/changelog", mod_list_changelog, name="mod-list-changelog"),
    path("lists/<slug:slug>/final", mod_list_final, name="mod-list-final"),
    path(
        "lists/<slug:slug>/<int:step>/",
        mod_list_step_detail,
        name="mod-list-step-detail",
    ),
    path(
        "lists/<slug:slug>/<int:step>/json",
        mod_list_step_detail,
        {"as_json": True},
        name="mod-list-step-detail-json",
    ),
    path(
        "load-order/", static_view, {"template": "load_order.html"}, name="load_order"
    ),
    # path('logout/', logout, {'template_name': 'logout.html'},
    #     name='logout'),
    path("media/", include("media.urls", namespace="media")),
    path("mods/", all_mods, name="mod_index"),
    path(
        "mods/add",
        static_view,
        {"template": "how-to-get-a-mod-added.html"},
        name="how-to-get-a-mod-added",
    ),
    path(
        "mods/todo/",
        legacy_url_redirect,
        {"new_slug": "total-overhaul", "new_view": "mod-list-detail"},
        name="mod_todo",
    ),
    path("mods/all/", all_mods, name="all_mods"),
    path("mods/all/json", all_mods, {"as_json": True}, name="all_mods"),
    path("mods/alts/", mod_alts, name="mod_alts"),
    path("mods/category/all/", categories, name="mod_categories"),
    # START preserve old category names
    path(
        "mods/category/followers/",
        legacy_url_redirect,
        {"new_slug": "companions", "new_view": "mod_category_detail"},
        name="followers-redirect",
    ),
    # END preserve old category names
    path("mods/category/<slug:slug>/", category_detail, name="mod_category_detail"),
    path("mods/latest/", latest_mods, name="latest_mods"),
    # START preserve old list URLs and ?step=100 endpoints
    path(
        "mods/list/",
        legacy_url_redirect,
        {"new_slug": "total-overhaul", "new_view": "mod-list-detail"},
        name="old-step1",
    ),
    path(
        "mods/steps/",
        # The legacy_url_redirect is not used here because the
        # redirect is handled in the mod_list_step_detail view.
        # This is to allow for handling of args like: ?step=42
        mod_list_step_detail,
        {"slug": "total-overhaul", "step": 1},
        name="old-step2",
    ),
    # Expanded vanilla:
    path(
        "mods/tag/expanded-vanilla/",
        legacy_url_redirect,
        {"new_slug": "expanded-vanilla", "new_view": "mod-list-detail"},
        name="old-step3",
    ),
    # TES3MP Friendly:
    path(
        "mods/tag/tes3mp-friendly/",
        legacy_url_redirect,
        {"new_slug": "tes3mp-server", "new_view": "mod-list-detail"},
        name="old-step4",
    ),
    # END preserve old list URLs and ?step=100 endpoints
    path("mods/tag/", tags, name="mod_tags"),
    # Preserve bad, old, typo, other links that are
    # now "gone" for any other reason.
    path(
        "mods/ast-eds-remastered/",
        legacy_url_redirect,
        {"new_slug": "ast-beds-remastered"},
        name="ast_beds_redirect",
    ),
    path(
        "mods/beautiful-cities-of-morrowind-patches-patch-for-pu/",
        legacy_url_redirect,
        {"new_slug": "beautiful-cities-of-morrowind"},
        name="bcom_patch_num_1",
    ),
    path(

momw/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %} | Modding OpenMW: A guide to modding and modernizing Morrowind with OpenMW</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block meta %}
    {% endblock %}
    <link rel="manifest" href="/manifest.webmanifest">
    {% if DEBUG %}
      {% load static %}
      <link rel="stylesheet" href="{% static 'css/normalize.css' %}" type="text/css">
      <link rel="stylesheet" href="{% static 'css/skeleton.css' %}" type="text/css">
      <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" type="text/css">
      <link rel="stylesheet" href="{% static 'css/site.css' %}" type="text/css">
      <link id="prefer-darkmode" media="(prefers-color-scheme: dark)" href="{% static 'css/site-dark.css' %}" type="text/css" rel="stylesheet"/>
      <link rel="icon" href="{% static 'favicon.png' %}">
    {% else  %}
      <link rel="stylesheet" href="/css/normalize.css" type="text/css">
      <link rel="stylesheet" href="/css/skeleton.css" type="text/css">
      <link rel="stylesheet" href="/css/font-awesome.min.css" type="text/css">
      <link rel="stylesheet" href="/css/site.css" type="text/css">
      <link id="prefer-darkmode" media="(prefers-color-scheme: dark)" href="/css/site-dark.css" type="text/css" rel="stylesheet"/>
      <link rel="icon" href="/favicon.png">
    {% endif %}
  </head>
  <body>
    {% if momw_ver %}<div class="bold center" id="banner"><i class="fa fa-exclamation-triangle" aria-hidden="true"></i> You are looking at the {{ momw_ver|upper }} version of this site (rev: <a href="https://gitlab.com/modding-openmw/modding-openmw.com/-/blob/{{ momw_sha }}">{{ momw_rev }}</a>).  More info <a href="{% url 'site-versions' %}">here</a>. <i class="fa fa-exclamation-triangle" aria-hidden="true"></i></div>{% endif %}
    {# <div class="bold center" id="status-banner">Please click <a href="{% url 'future_plans' %}">here</a> for a message from the site maintainer about the website's future</div> #}
    <!--
         Hello, outlander!  What are you doing in here?!
    -->
    {% block header %}{% include 'header.html' %}{% endblock %}

    <div class="line"></div>

    <div id="content">{% block content %}{% endblock %}</div>

    {% if DEBUG %}{% block ddeebbuugg %}{% endblock %}{% endif %}

    <div class="line"></div>

    {% include 'footer.html' %}

    {% block lower_js %}{% endblock %}

    {% if DEBUG %}
      <script src="{% static 'js/yesdev.js' %}"></script>
      <script src="{% static 'js/set-basedir.js' %}"></script>
      <script src="{% static 'js/set-mwdir.js' %}"></script>
      <script src="{% static 'js/theme-picker.js' %}"></script>
    {% else %}
      <script src="/js/yesdev.js"></script>
      <script src="/js/set-basedir.js"></script>
      <script src="/js/set-mwdir.js"></script>
      <script src="/js/theme-picker.js"></script>
    {% endif %}

    {% if not no_focus %}
      <script>
       // Don't break anchor/hash links
       if (window.location.hash === "")
         document.search.q.focus();
      </script>
    {% endif %}

    {% include 'tracking.html' %}
  </body>
</html>

momw/templates/category_index.html
{% extends 'base.html' %}
{% block title %}Categories{% endblock %}
{% block content %}
  <div>
    <h3 class="bold center">Categories</h3>
    {% for c in categories %}
      {% include "category_snippet.html" with category=c %}
    {% endfor %}
    {% include 'paginate.html' %}
  </div>
{% endblock %}

momw/templates/category_snippet.html
<div>
  <div>
    <h5 class="bold"><a href="{{ category.get_absolute_url }}">{{ category.title }}</a></h5>
  </div>
  <div>
    {{ category.description }}
  </div>
</div>

momw/templates/contact.html
{% extends 'base.html' %}
{% block title %}Contact{% endblock %}
{% block content %}
  {% if form.errors %}
    <div id="contact_errors" class="alert alert-danger center">
      <p id="contact_error_msg" class="center">Wait!</p>
      <p class="center errormsg">You must correct the following error{{ form.errors|pluralize }} before you can contact me:</p>
      {% if form.name.errors %}<span class="bold">{{ form.name.errors }}</span>{% endif %}
      {% if form.email.errors %}<span class="bold">{{ form.email.errors }}</span>{% endif %}
      {% if form.message.errors %}<span class="bold">{{ form.message.errors }}</span>{% endif %}
    </div>
  {% endif %}
  <div id="contact">
    {% if not sent %}
      <h2 class="center">Contact</h2>
      <p class="bold" style="font-size: 1.4em;">
        Thanks for visiting. Please note that the website maintainer has a significant email backlog and it may take a very long time to get a response. Please feel free to <a href="https://discord.gg/KYKEUxFUsZ">join the Discord channel</a> or <a href="https://web.libera.chat/?channels=#momw">IRC</a> in order to chat with the community. If you've sent an email and waited for a response, sorry about the wait!
      </p>
      <p class="center">Please fill out the form and click "Submit" below to send your message.</p>
      <form id="contact" action="." method="post">{% csrf_token %}
        <div class="row">
          <div class="six columns">
            <label for="{{ form.name.id_for_label }}">{{ form.name.label }}</label>
            <input class="u-full-width" id="{{ form.name.id_for_label }}" name="{{ form.name.name }}" type="text" placeholder="Your {{ form.name.label }}" required>
          </div>
          <div class="six columns">
            <label for="{{ form.email.id_for_label }}">{{ form.email.label }}</label>
            <input class="u-full-width" id="{{ form.email.id_for_label }}" name="{{ form.email.name }}" type="email" placeholder="Your {{ form.email.label }}" required>
          </div>
        </div>
        <label for="{{ form.message.id_for_label }}">{{ form.message.label }}</label>
        <textarea class="u-full-width" id="{{ form.message.id_for_label }}" name="{{ form.message.name }}" placeholder="Your {{ form.message.label }}" required>{% if msg %}{{ msg }}{% endif %}</textarea>
        <button class="button u-full-width" id="contact">Submit</button>
      </form>
      <p class="center">You may also send an email to <a class="bold" id="mail_goes_here">contact at modding-openmw dot com</a>.</p>
    {% else %}
      <h3 class="center" style="margin-bottom: 300px;">Thanks for reaching out!</h3>
    {% endif %}
  </div>
  {% include "main-nav.html" with cur_page="contact" %}
{% endblock %}
{% block lower_js %}
  {% if DEBUG %}
    {% load static %}
    <script src="{% static 'js/theme-picker.js' %}"></script>
  {% else %}
    <script src="/js/theme-picker.js"></script>
  {% endif %}
  <script type="text/javascript">
   (function(){
     const u = "contact";
     const d = "modding-openmw";
     const t = "com";
     document.getElementById("mail_goes_here").href = 'mailto:' + u + "@" + d + "." + t;
   })();
  </script>

{% endblock %}

momw/templates/entries_by_day.html
{% extends 'base.html' %}
{% block title %}{{ day|date:'d M, Y' }}{% endblock %}
{% block content %}
  <div>
    <h3 class="bold center">{{ day|date:'d M, Y' }}</h3>
    {% for e in entries_by_day %}
      {% include "item_snippet.html" with item=e %}
    {% endfor %}
  </div>
  {% include "paginate.html" %}
{% endblock %}

momw/templates/entries_by_month.html
{% extends 'base.html' %}
{% block title %}{{ month|date:'M, Y' }}{% endblock %}
{% block content %}
  <div>
    <h3 class="bold center">{{ month|date:'M, Y' }}</h3>
    {% for e in entries_by_month %}
      {% include "item_snippet.html" with item=e %}
    {% endfor %}
  </div>
  {% include "paginate.html" %}
{% endblock %}

momw/templates/entry_header.html
<div>
  <h3 class="bold">{{ item.title }}</h3>
</div>
<div>
  {# <a class="bold" href="{% url 'blog:by_year' item.date_added|date:'Y' %}">{{ item.date_added|date:'Y' }}</a>-<a class="bold" href="{% url 'blog:by_month' item.date_added|date:'Y' item.date_added|date:'m' %}">{{ item.date_added|date:"m" }}</a>-<a class="bold" href="{% url 'blog:by_day' item.date_added|date:'Y' item.date_added|date:'m' item.date_added|date:'d' %}">{{ item.date_added|date:"d" }}</a> | by <span class="bold">{{ item.author.first_name }} {{ item.author.last_name }}</span> #}
  <span class="bold">{{ item.date_added|date:'Y' }}-{{ item.date_added|date:'m' }}-{{ item.date_added|date:'d' }}</span> | by <span class="bold">{{ item.author.first_name }} {{ item.author.last_name }}</span>
  {% if item.category  %}under <a class="bold" href="{% url 'blog:category_detail' item.category.slug %}">{{ item.category }}</a>{% endif %}
</div>
{% if item.tags and item.tags.count > 0 %}
  <div>
    <a href="{% url 'blog:tag_cloud' %}">Tag{{ item.tags.all|pluralize }}</a>: {% for t in item.tags.all %}<a href="{{ t.get_absolute_url }}">{{ t }}</a>{% if not forloop.last %}, {% endif %}{% endfor %}
  </div>
{% endif %}
<div class="entry-body">
  {% if item.excerpt %}
    <div>
      {{ item.excerpt|safe }}
    </div>
  {% endif %}
  <div>
    {{ item.body|safe }}
  </div>
</div>

momw/templates/latest_media_rss_link.html
<a href="{% url 'media:latest_media_feed' %}">
  <span class="fa fa-rss-square"></span> <span class="bold text-muted">Subscribe to the media feed!</span>
</a>

momw/templates/live_asciinema.html
{% extends 'base.html' %}
{% block title %}Asciinema Clips{% endblock %}
{% block content %}
  <div>
    <h3>Asciinema Clips</h3>
  </div>
  {% if live_asciinema %}
    {% for a in live_asciinema %}
      <div>
        <h5 class="bold"><a href="{% url 'media:detail' a.slug %}">{{ a.title }}</a></h5>
        <div>Posted on {{ a.date_added|date:'Y' }}-{{ a.date_added|date:"m" }}-{{ a.date_added|date:"d" }}</div>
        <p>{{ a.description|safe }}</p>
      </div>
      {% if not forloop.last %}
        <div class="center small-divider"></div>
      {% endif %}
    {% endfor %}
  {% else %}
    <h5 class="center">Coming soon..</h5>
    <p class="img"><img class="center" src="/i/soon.jpg" /></p>
  {% endif %}
  {% include 'paginate.html' %}
{% endblock %}

momw/templates/live_audio.html
{% extends 'base.html' %}
{% block title %}Modding-OpenMW.com Podcast{% endblock %}
{% block content %}
  <div class="center">
    <h3>Modding-OpenMW.com Podcast</h3>
    <p>Audio clips, also known as a podcast.  Let's talk about all things OpenMW!</p>
  </div>
  {% if live_audio %}
    {% for a in live_audio %}
      <div>
        <h5 class="bold"><a href="{% url 'media:detail' a.slug %}">{{ a.title }}</a></h5>
        <div>Posted on {{ a.date_added|date:'Y' }}-{{ a.date_added|date:"m" }}-{{ a.date_added|date:"d" }}</div>
        <div>{{ a.description|safe|truncatewords:30 }}</div>
      </div>
    {% endfor %}
  {% else %}
    <h5 class="center">Coming soon..</h5>
    <p class="img"><img class="center" src="/i/soon.jpg" /></p>
  {% endif %}
  {% include 'paginate.html' %}
{% endblock %}

momw/templates/live_images.html
{% extends 'base.html' %}
{% block title %}Images{% endblock %}
{% block content %}
  <div class="center">
    <h3>Images</h3>
    <p>Images of gameplay and various mods featured here.</p>
  </div>

  <div style="padding-bottom: 100px;">
    {% for i in images %}
    <div>
      <div style="clear: left;">
        <a style="padding-bottom: 30px; float: left; padding-right: 10px;" href="{% url 'media:detail' i.slug %}">{{ i.media_link_300200|safe }}</a>
        <h5 class="bold"><a href="{% url 'media:detail' i.slug %}">{{ i.title }}</a></h5>
        <div>Posted on {{ i.date_added|date:'Y' }}-{{ i.date_added|date:"m" }}-{{ i.date_added|date:"d" }}</div>
        <p>{{ i.description|safe }}</p>
      </div>
    </div>
    {% endfor %}
  </div>
  {% include 'paginate.html' %}
{% endblock %}

momw/templates/live_video.html
{% extends 'base.html' %}
{% block title %}Video Clips{% endblock %}
{% block content %}
  <div class="center">
    <h3>Video Clips</h3>
  </div>
  <div style="padding-bottom: 100px;">
    {% for v in live_video %}
      <div>
        <div style="clear: left;">
          <a style="float: left; padding-right: 10px;" href="{% url 'media:detail' v.slug %}">{{ v.media_link_300200|striptags }}</a>
          <h5 class="bold"><a href="{% url 'media:detail' v.slug %}">{{ v.title }}</a></h5>
          <div>Posted on {{ v.date_added|date:'Y' }}-{{ v.date_added|date:"m" }}-{{ v.date_added|date:"d" }}</div>
          <p>{{ v.description|striptags|truncatewords:14 }}</p>
        </div>
      </div>
    {% endfor %}
  </div>
  {% include 'paginate.html' %}
{% endblock %}

momw/templates/tag_cloud.html
{% extends 'base.html' %}
{% block title %}Tags{% endblock %}
{% block content %}
  <div class="center">
    <h2 class="bold center">Tags</h2>
    {% for t in tags %}
      <span style="font-size: {{ t.tag_cloud_size }}em;"><a class="tag_cloud_tag" href="{{ t.get_absolute_url }}">{{ t }}</a></span>{% if not forloop.last %}&nbsp;{% endif %}
    {% endfor %}
  </div>
{% endblock %}